name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }} hchunhui/librime-lua lotem/librime-octagram rime/librime-predict
  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }} hchunhui/librime-lua lotem/librime-octagram rime/librime-predict
